openapi: 3.0.1
info:
  title: Central Api Subjects
  version: 0.1.0
servers:
- url: "{server}:{port}/central/api/subjects"
  variables:
    server:
      default: http://localhost
    port:
      default: "9094"
paths:
  /:
    get:
      operationId: get
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
    put:
      operationId: put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ID'
        required: true
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
        "401":
          description: Unauthorized
    delete:
      operationId: delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ID'
        required: true
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
        "401":
          description: Unauthorized
  /goals:
    put:
      operationId: putGoals
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoalAdjust'
        required: true
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
        "401":
          description: Unauthorized
  /{subjectId}:
    get:
      operationId: getSubjectid
      parameters:
      - name: subjectId
        in: path
        required: true
        schema:
          type: string
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyStatus'
        "401":
          description: Unauthorized
        "404":
          description: NotFound
  /{subjectId}/{year}/{weekNo}:
    get:
      operationId: getSubjectidYearWeekno
      parameters:
      - name: subjectId
        in: path
        required: true
        schema:
          type: string
      - name: year
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: weekNo
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "500":
          description: InternalServerError
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyStatus'
        "401":
          description: Unauthorized
        "404":
          description: NotFound
components:
  schemas:
    GoalAdjust:
      required:
      - goalHours
      - subjectId
      type: object
      properties:
        subjectId:
          type: string
        goalHours:
          type: number
          format: double
      additionalProperties: false
    ID:
      required:
      - id
      type: object
      properties:
        id:
          type: string
      additionalProperties: false
    Lesson:
      required:
      - id
      - name
      - "no"
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        "no":
          type: integer
          format: int64
      additionalProperties: false
    StudyStatus:
      required:
      - actualHours
      - goalHours
      - lessonDates
      - lessons
      - studentId
      - studiedLessons
      - subjectId
      - weekNo
      - year
      type: object
      properties:
        studentId:
          type: string
        subjectId:
          type: string
        weekNo:
          type: integer
          format: int64
        year:
          type: integer
          format: int64
        actualHours:
          type: number
          format: double
        goalHours:
          type: number
          format: double
          nullable: true
        lessonDates:
          type: object
          additionalProperties:
            type: string
          nullable: true
        studiedLessons:
          type: array
          nullable: true
          items:
            type: string
        lessons:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Lesson'
      additionalProperties: false
    Subject:
      required:
      - id
      - lessons
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lessons:
          type: array
          items:
            $ref: '#/components/schemas/Lesson'
      additionalProperties: false
