openapi: 3.0.1
info:
  title: Central Api Study
  version: 0.1.0
servers:
- url: "{server}:{port}/central/api/study"
  variables:
    server:
      default: http://localhost
    port:
      default: "9094"
paths:
  /:
    post:
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudySession'
        required: true
      responses:
        "500":
          description: InternalServerError
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyStatus'
        "401":
          description: Unauthorized
        "404":
          description: NotFound
components:
  schemas:
    Lesson:
      required:
      - id
      - name
      - "no"
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        "no":
          type: integer
          format: int64
      additionalProperties: false
    StudySession:
      required:
      - lessonId
      - noMins
      - subjectId
      type: object
      properties:
        subjectId:
          type: string
        lessonId:
          type: string
        noMins:
          type: integer
          format: int64
      additionalProperties: false
    StudyStatus:
      required:
      - actualHours
      - goalHours
      - lessonDates
      - lessons
      - studentId
      - studiedLessons
      - subjectId
      - weekNo
      - year
      type: object
      properties:
        studentId:
          type: string
        subjectId:
          type: string
        weekNo:
          type: integer
          format: int64
        year:
          type: integer
          format: int64
        actualHours:
          type: number
          format: double
        goalHours:
          type: number
          format: double
          nullable: true
        lessonDates:
          type: object
          additionalProperties:
            type: string
          nullable: true
        studiedLessons:
          type: array
          nullable: true
          items:
            type: string
        lessons:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Lesson'
      additionalProperties: false
