@testtoken = 

@harithatoken = 

@rashmitoken = 

@saginitoken = 

@piruthutoken = 

@noexisttoken = 

@saginiId = 67063966256a7bdef77db020

@harithaId = 67063947256a7bdef77db007

@rashmiId = 6706392e256a7bdef77daff2

@piruthuId = 6706398247b6e10d8cd4245e

@token = {{rashmitoken}}

### Create User
POST http://localhost:9094/central/api/users
Authorization: Bearer {{token}}

{
    "id": "6706392e256a7bdef77daff2",
    "name": "Ravichandran Piruthuviraj",
    "email": "piruthuviraj@hikari.com"
}

### User Details
GET http://localhost:9094/central/api/users
Authorization: Bearer {{noexisttoken}}

### Enroll Subject
PUT http://localhost:9094/central/api/subjects
Authorization: Bearer {{token}}

{
    "id": "01ef813a-7e5e-1c10-81bf-c2a58dd33537"
}

### Unenroll Subject
DELETE http://localhost:9094/central/api/subjects
Authorization: Bearer {{token}}

{
    "id": "01ef813a-7e5e-1c10-81bf-c2a58dd33537"
}

### Adjust Goal Hours
PUT http://localhost:9094/central/api/subjects/goals
Authorization: Bearer {{token}}

{
    "subjectId": "01ef813a-7e5e-1c10-81bf-c2a58dd33537",
    "goalHours": 2
}

### Study Status
GET http://localhost:9094/central/api/subjects/01ef813a-7e5e-1c10-81bf-c2a58dd33537
Authorization: Bearer {{token}}

### Study Status Specific Week
GET http://localhost:9094/central/api/subjects/01ef813a-7e5e-1c10-81bf-c2a58dd33537/2024/40
Authorization: Bearer {{token}}

### Record Study Session
POST http://localhost:9094/central/api/study
Authorization: Bearer {{token}}

{
    "subjectId": "01ef813a-7e5e-1c10-81bf-c2a58dd33537",
    "lessonId": "01ef8201-0c9d-19ae-b130-e73ce32c95db",
    "noMins": 30
}

### Search Users
GET http://localhost:9094/central/api/users/search/pir
Authorization: Bearer {{token}}

### Friend Details
GET http://localhost:9094/central/api/users/friends
Authorization: Bearer {{token}}

### Make friend request
PUT http://localhost:9094/central/api/users/friend-request
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Accept friend request
PUT http://localhost:9094/central/api/users/accept-friend-request
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Reject friend request (When the logged in user rejects the request by someone else)
DELETE http://localhost:9094/central/api/users/reject-friend-request
Authorization: Bearer {{token}}

{
    "id": "6706398247b6e10d8cd4245e"
}

### Revoke friend request (When the logged in user revokes the request sent to someone else)
DELETE http://localhost:9094/central/api/users/friend-request
Authorization: Bearer {{token}}

{
    "id": "6706392e256a7bdef77daff2"
}

### Unfollow a friend
DELETE http://localhost:9094/central/api/users/follow-friend
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Remove a follower
DELETE http://localhost:9094/central/api/users/friend-follower
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Get all subjects
GET http://localhost:9094/central/api/subjects
Authorization: Bearer {{token}}
