@testtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNyQjE4ejFjRDB2QUticm1FamZ4diJ9.eyJpc3MiOiJodHRwczovL2hpa2FyaS51ay5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjZmYmMxZjFlM2E2YmIzNzVkNmI5MzFjIiwiYXVkIjpbImNlbnRyYWxfYXBpIiwiaHR0cHM6Ly9oaWthcmkudWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcyODQ2MTkxMiwiZXhwIjoxNzI4NTQ4MzEyLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRWRRRUVMd0tRWVhPS2I4V2htck0zZHpPNzN0MkxyTGYifQ.ARr3yJsQc01zCVyFk-KrZUfoXMlvIFUm7xOhybs3CVZn-siFBVwuuaAJweYNWlp3ttHSkUx5K3b_gmcXFdO3BCwXpSiKZGowcZUx50ICmv4trd-bbwEzogWrqdf4Yc_l1Qq5RuetYzFSbsubO8Y1lNANChqLkpBxgkX6H90NY2xrW2ccm3dP-Tsvbv__SPy-W56o0tfe-Pu9YW6ZCvym5LBsAmZbSAwccOTsg1Z8XCZ2QfBrDBmxTDMCY0FaNRHe8dON0bIdBMn34RxKDU9eFnxtzZJlA5UOsjWCfXU4gfpw74ucuSxYI98v6aUg-ik-rZHi9Y9nFoUQpVBcxh5vyA

@harithatoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNyQjE4ejFjRDB2QUticm1FamZ4diJ9.eyJpc3MiOiJodHRwczovL2hpa2FyaS51ay5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjcwNjM5NDcyNTZhN2JkZWY3N2RiMDA3IiwiYXVkIjpbImNlbnRyYWxfYXBpIiwiaHR0cHM6Ly9oaWthcmkudWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcyODQ2Mjg2NSwiZXhwIjoxNzI4NTQ5MjY1LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRWRRRUVMd0tRWVhPS2I4V2htck0zZHpPNzN0MkxyTGYifQ.pW9UKn6JeYiYAzVtOkQXqXSAESrZN_EsT3XoV56_4U7yu10CzgA8mUK2q2lR-DQbEX9b7dMBnf3wX65p_QXBst9ssYHn_cOSa-nF-wHy0DMoxbRO5o9obt7H0f6zRJdH-uiNCajWhSLFsMhz4s8nem8tCtxwzMOnFv0IY21Be2r1S5jfviyHaMpvLoZyv2k3n0Of08JfMiXekJFgSLdERhUFggtCFaOdIfhFJ7-dOrRi8m8FXl78mCGXnlHuH7OvuEUhHdsMxpzXqHCQs5rGRmjaFhkQHiiD9Dt5NM_yKhFvT6d3_FO72obx4k469VoSJno5T-yGgXzufHSYArDNcg

@rashmitoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNyQjE4ejFjRDB2QUticm1FamZ4diJ9.eyJpc3MiOiJodHRwczovL2hpa2FyaS51ay5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjcwNjM5MmUyNTZhN2JkZWY3N2RhZmYyIiwiYXVkIjpbImNlbnRyYWxfYXBpIiwiaHR0cHM6Ly9oaWthcmkudWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcyODQ2Mjc1MywiZXhwIjoxNzI4NTQ5MTUzLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRWRRRUVMd0tRWVhPS2I4V2htck0zZHpPNzN0MkxyTGYifQ.UbpHqCr60xun54KOhkgCjkZ2fUSOlEX7-SruFTB3pDoWXz4nscX4kvY-iW3FQ2ECRPVZeEB_MrlKBJO2b_4Mk3b2Y7YNdZOgbWnPZJbji0NZtKX62uuL5GH5UsxLphM6_nggfAIBWnUH_8mXJt0GiP4xls8kKuUd-hZDcHITG0IRaDVlPTwA0ZWESfewbM16BMuPUZTH5i-0vncjc0P6lbihHxkpDq8dYkQ_M1DmIzhXF14fkQbQ0DOxaF9JzcJvYrmTa5U3_XPN-gexNRktATGfYMSTJNA59WO11j4Y1L8SPlH4mwAZX0gRxxIEqu4iMILvf07sL82d3pOtF3bAgA

@saginitoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNyQjE4ejFjRDB2QUticm1FamZ4diJ9.eyJpc3MiOiJodHRwczovL2hpa2FyaS51ay5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjcwNjM5NjYyNTZhN2JkZWY3N2RiMDIwIiwiYXVkIjpbImNlbnRyYWxfYXBpIiwiaHR0cHM6Ly9oaWthcmkudWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcyODUzMTM4NSwiZXhwIjoxNzI4NjE3Nzg1LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRWRRRUVMd0tRWVhPS2I4V2htck0zZHpPNzN0MkxyTGYifQ.lJj7bdrztnGFehQub01dCAhmHbJ73tBkrBkCtfHFdafLc0Oe5S2GdDXRS_HfYB4KKg0-_DF51PGY7y8cCAOKFuU8axKErroZ5fKqR4g3IVmGEgdGXuboDUNG4gMrWfgWIOJgZVCzXjraPkpTCT39csUCzdongUa9qu_rAoc1wPemjnxgrdn_u2nRRxNaJK51_wAC_BZnTgy25ajO3NJXV9MF3rmYH3O39Eki7txSBSFrTKvHBq4CfF0d2n1BhicDDeiyCnHlUUS1-HlDGGv1OwzSp85xaThexb83ytyTvMW5QnTzWfx9eoQCUN2AxI0k6WvSa519FLORbSPe4MhVNQ

@piruthutoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlNyQjE4ejFjRDB2QUticm1FamZ4diJ9.eyJpc3MiOiJodHRwczovL2hpa2FyaS51ay5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjcwNjM5ODI0N2I2ZTEwZDhjZDQyNDVlIiwiYXVkIjpbImNlbnRyYWxfYXBpIiwiaHR0cHM6Ly9oaWthcmkudWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcyODUzMTQ3MiwiZXhwIjoxNzI4NjE3ODcyLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRWRRRUVMd0tRWVhPS2I4V2htck0zZHpPNzN0MkxyTGYifQ.EBf2w3qtqcYYkg_SuY9QlJiF-4ETulBK-NscKTBdq3db2AKdllcQKzwEI2V2TN_ef-NRxJBvBWRePshyMuBbjFLxE9vF5hMZvUhLvhehiIxptJD72mebt-xS1IfVLOdelq3yMrhAJud9NkSNUPgPD5791uApydB7yjr8ffdA94c_A1Fdu3CN4I94PmZrmjtLNGuEkL3iy_HHvYZbs3NGbMS5-mRLUCqquKXO0kZq0Dzbkfh5zUMQbRFjvAULaQj9CROY5M4KZ-cbp9wJ-8ot9aTElQwsDgiKeIe8rGPgCYBtetL5FYrXF2iwlOjOnBsZtzDvukxdJ8WGaSViuKxPGA

@saginiId = 67063966256a7bdef77db020

@harithaId = 67063947256a7bdef77db007

@rashmiId = 6706392e256a7bdef77daff2

@piruthuId = 6706398247b6e10d8cd4245e

@token = {{rashmitoken}}

### Create User
POST http://localhost:9094/central/api/users
Authorization: Bearer {{token}}

{
    "name": "Ravichandran Piruthuviraj",
    "email": "piruthuviraj@hikari.com"
}

### User Details
GET http://localhost:9094/central/api/users
Authorization: Bearer {{token}}

### Enroll Subject
PUT http://localhost:9094/central/api/subjects
Authorization: Bearer {{token}}

{
    "id": "01ef813a-7e5e-1c10-81bf-c2a58dd33537"
}

### Unenroll Subject
DELETE http://localhost:9094/central/api/subjects
Authorization: Bearer {{token}}

{
    "id": "01ef813a-7e5e-1c10-81bf-c2a58dd33537"
}

### Adjust Goal Hours
PUT http://localhost:9094/central/api/subjects/goals
Authorization: Bearer {{token}}

{
    "subjectId": "01ef813a-7e5e-1c10-81bf-c2a58dd33537",
    "goalHours": 11
}

### Study Status
GET http://localhost:9094/central/api/subjects/01ef813a-7e5e-1c10-81bf-c2a58dd33537
Authorization: Bearer {{token}}

### Study Status Specific Week
GET http://localhost:9094/central/api/subjects/01ef813a-7e5e-1c10-81bf-c2a58dd33537/2024/40
Authorization: Bearer {{token}}

### Record Study Session
POST http://localhost:9094/central/api/study
Authorization: Bearer {{token}}

{
    "subjectId": "01ef813a-3213-1816-b7e7-efedfe66b24b",
    "lessonId": "01ef8201-0c9d-17ae-b130-e73ce32c95db",
    "noMins": 30
}

### Friend Details
GET http://localhost:9094/central/api/users/friends
Authorization: Bearer {{token}}

### Make friend request
PUT http://localhost:9094/central/api/users/friend-request
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Accept friend request
PUT http://localhost:9094/central/api/users/accept-friend-request
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

### Reject friend request (When the logged in user rejects the request by someone else)
DELETE http://localhost:9094/central/api/users/reject-friend-request
Authorization: Bearer {{token}}

{
    "id": "6706398247b6e10d8cd4245e"
}

### Revoke friend request (When the logged in user revokes the request sent to someone else)
DELETE http://localhost:9094/central/api/users/friend-request
Authorization: Bearer {{token}}

{
    "id": "6706392e256a7bdef77daff2"
}

### Unfollow a friend
DELETE http://localhost:9094/central/api/users/follow-friend
Authorization: Bearer {{token}}

{
    "id": "67063966256a7bdef77db020"
}

### Remove a follower
DELETE http://localhost:9094/central/api/users/friend-follower
Authorization: Bearer {{token}}

{
    "id": "{{saginiId}}"
}

###



# https://hikari.uk.auth0.com/authorize?response_type=code&client_id=EdQEELwKQYXOKb8WhmrM3dzO73t2LrLf&redirect_uri=http://localhost:3000&scope=openid profile email&audience=central_api&state=sldkfjsdlfjwoeijflskdjfowiejf
# http://localhost:3000/?code=6raK5Dhjai0tK7LwyZhM8xL72GTdQ7rxeJt7hmuo5RKfJ&state=sldkfjsdlfjwoeijflskdjfowiejf

curl --request POST \
  --url 'https://hikari.uk.auth0.com/oauth/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=authorization_code \
  --data 'client_id=EdQEELwKQYXOKb8WhmrM3dzO73t2LrLf' \
  --data 'client_secret=QIMWclKJRknZwrFOehvs3SmDjpibp3wBN8x0Yvxak4P4ehO4yaXaCRA2EcQ7bnSK' \
  --data 'code=6raK5Dhjai0tK7LwyZhM8xL72GTdQ7rxeJt7hmuo5RKfJ' \
  --data 'redirect_uri=http://localhost:3000'